//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS_API.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings:ApiHost.
        /// </summary>
        public static string AppSettings_ApiHost {
            get {
                return ResourceManager.GetString("AppSettings_ApiHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings:ItemsBulkImportSampleFile.
        /// </summary>
        public static string AppSettings_ItemsBulkImportSampleFile {
            get {
                return ResourceManager.GetString("AppSettings_ItemsBulkImportSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings:RootFolder.
        /// </summary>
        public static string AppSettings_RootFolder {
            get {
                return ResourceManager.GetString("AppSettings_RootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgs/CategoryImages.
        /// </summary>
        public static string CategoryImagesFolder {
            get {
                return ResourceManager.GetString("CategoryImagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.png.
        /// </summary>
        public static string DEFAULT_IMAGE {
            get {
                return ResourceManager.GetString("DEFAULT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgs/ItemImages.
        /// </summary>
        public static string ItemImagesFolder {
            get {
                return ResourceManager.GetString("ItemImagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgs/SubCategoryImages.
        /// </summary>
        public static string SubCategoryImagesFolder {
            get {
                return ResourceManager.GetString("SubCategoryImagesFolder", resourceCulture);
            }
        }
    }
}
