//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserRights {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRights() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.UserRights", typeof(UserRights).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNewJournalEntry.
        /// </summary>
        public static string AddNewJournalEntry {
            get {
                return ResourceManager.GetString("AddNewJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddPhysicalStock.
        /// </summary>
        public static string AddPhysicalStock {
            get {
                return ResourceManager.GetString("AddPhysicalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BalanceSheet.
        /// </summary>
        public static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicSalesReports.
        /// </summary>
        public static string BasicSalesReports {
            get {
                return ResourceManager.GetString("BasicSalesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillDetails.
        /// </summary>
        public static string BillDetails {
            get {
                return ResourceManager.GetString("BillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchDetails.
        /// </summary>
        public static string BranchDetails {
            get {
                return ResourceManager.GetString("BranchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandDetails.
        /// </summary>
        public static string BrandDetails {
            get {
                return ResourceManager.GetString("BrandDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelOrder.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorDetails.
        /// </summary>
        public static string ColorDetails {
            get {
                return ResourceManager.GetString("ColorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanySetup.
        /// </summary>
        public static string CompanySetup {
            get {
                return ResourceManager.GetString("CompanySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAccount.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBranch.
        /// </summary>
        public static string CreateBranch {
            get {
                return ResourceManager.GetString("CreateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBrand.
        /// </summary>
        public static string CreateBrand {
            get {
                return ResourceManager.GetString("CreateBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateColor.
        /// </summary>
        public static string CreateColor {
            get {
                return ResourceManager.GetString("CreateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDeliveryBoy.
        /// </summary>
        public static string CreateDeliveryBoy {
            get {
                return ResourceManager.GetString("CreateDeliveryBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDeliveryServiceVendor.
        /// </summary>
        public static string CreateDeliveryServiceVendor {
            get {
                return ResourceManager.GetString("CreateDeliveryServiceVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDiningTable.
        /// </summary>
        public static string CreateDiningTable {
            get {
                return ResourceManager.GetString("CreateDiningTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateGRN.
        /// </summary>
        public static string CreateGRN {
            get {
                return ResourceManager.GetString("CreateGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateGRRN.
        /// </summary>
        public static string CreateGRRN {
            get {
                return ResourceManager.GetString("CreateGRRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateItem.
        /// </summary>
        public static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateItemBarCode.
        /// </summary>
        public static string CreateItemBarCode {
            get {
                return ResourceManager.GetString("CreateItemBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateMainCategory.
        /// </summary>
        public static string CreateMainCategory {
            get {
                return ResourceManager.GetString("CreateMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateModifier.
        /// </summary>
        public static string CreateModifier {
            get {
                return ResourceManager.GetString("CreateModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePO.
        /// </summary>
        public static string CreatePO {
            get {
                return ResourceManager.GetString("CreatePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePurchase.
        /// </summary>
        public static string CreatePurchase {
            get {
                return ResourceManager.GetString("CreatePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRestaurantFloor.
        /// </summary>
        public static string CreateRestaurantFloor {
            get {
                return ResourceManager.GetString("CreateRestaurantFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRole.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSize.
        /// </summary>
        public static string CreateSize {
            get {
                return ResourceManager.GetString("CreateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSubCategory.
        /// </summary>
        public static string CreateSubCategory {
            get {
                return ResourceManager.GetString("CreateSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateTax.
        /// </summary>
        public static string CreateTax {
            get {
                return ResourceManager.GetString("CreateTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUnit.
        /// </summary>
        public static string CreateUnit {
            get {
                return ResourceManager.GetString("CreateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUser.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateVendor.
        /// </summary>
        public static string CreateVendor {
            get {
                return ResourceManager.GetString("CreateVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateWaiter.
        /// </summary>
        public static string CreateWaiter {
            get {
                return ResourceManager.GetString("CreateWaiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteBranch.
        /// </summary>
        public static string DeleteBranch {
            get {
                return ResourceManager.GetString("DeleteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteBrand.
        /// </summary>
        public static string DeleteBrand {
            get {
                return ResourceManager.GetString("DeleteBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteColor.
        /// </summary>
        public static string DeleteColor {
            get {
                return ResourceManager.GetString("DeleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDeliveryBoy.
        /// </summary>
        public static string DeleteDeliveryBoy {
            get {
                return ResourceManager.GetString("DeleteDeliveryBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDeliveryServiceVendor.
        /// </summary>
        public static string DeleteDeliveryServiceVendor {
            get {
                return ResourceManager.GetString("DeleteDeliveryServiceVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDiningTable.
        /// </summary>
        public static string DeleteDiningTable {
            get {
                return ResourceManager.GetString("DeleteDiningTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteGRN.
        /// </summary>
        public static string DeleteGRN {
            get {
                return ResourceManager.GetString("DeleteGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteGRRN.
        /// </summary>
        public static string DeleteGRRN {
            get {
                return ResourceManager.GetString("DeleteGRRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteItem.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteItemBarCode.
        /// </summary>
        public static string DeleteItemBarCode {
            get {
                return ResourceManager.GetString("DeleteItemBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMainCategory.
        /// </summary>
        public static string DeleteMainCategory {
            get {
                return ResourceManager.GetString("DeleteMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteModifier.
        /// </summary>
        public static string DeleteModifier {
            get {
                return ResourceManager.GetString("DeleteModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletePO.
        /// </summary>
        public static string DeletePO {
            get {
                return ResourceManager.GetString("DeletePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletePurchase.
        /// </summary>
        public static string DeletePurchase {
            get {
                return ResourceManager.GetString("DeletePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRestaurantFloor.
        /// </summary>
        public static string DeleteRestaurantFloor {
            get {
                return ResourceManager.GetString("DeleteRestaurantFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRole.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSize.
        /// </summary>
        public static string DeleteSize {
            get {
                return ResourceManager.GetString("DeleteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSubCategory.
        /// </summary>
        public static string DeleteSubCategory {
            get {
                return ResourceManager.GetString("DeleteSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteTax.
        /// </summary>
        public static string DeleteTax {
            get {
                return ResourceManager.GetString("DeleteTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteUnit.
        /// </summary>
        public static string DeleteUnit {
            get {
                return ResourceManager.GetString("DeleteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteUser.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteVendor.
        /// </summary>
        public static string DeleteVendor {
            get {
                return ResourceManager.GetString("DeleteVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteWaiter.
        /// </summary>
        public static string DeleteWaiter {
            get {
                return ResourceManager.GetString("DeleteWaiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryBoyDetails.
        /// </summary>
        public static string DeliveryBoyDetails {
            get {
                return ResourceManager.GetString("DeliveryBoyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryBoys.
        /// </summary>
        public static string DeliveryBoys {
            get {
                return ResourceManager.GetString("DeliveryBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryServices.
        /// </summary>
        public static string DeliveryServices {
            get {
                return ResourceManager.GetString("DeliveryServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryServiceVendorDetails.
        /// </summary>
        public static string DeliveryServiceVendorDetails {
            get {
                return ResourceManager.GetString("DeliveryServiceVendorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryServiceVendors.
        /// </summary>
        public static string DeliveryServiceVendors {
            get {
                return ResourceManager.GetString("DeliveryServiceVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiningTableDetails.
        /// </summary>
        public static string DiningTableDetails {
            get {
                return ResourceManager.GetString("DiningTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiningTables.
        /// </summary>
        public static string DiningTables {
            get {
                return ResourceManager.GetString("DiningTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAccount.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditBranch.
        /// </summary>
        public static string EditBranch {
            get {
                return ResourceManager.GetString("EditBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditBrand.
        /// </summary>
        public static string EditBrand {
            get {
                return ResourceManager.GetString("EditBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditColor.
        /// </summary>
        public static string EditColor {
            get {
                return ResourceManager.GetString("EditColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditDeliveryBoy.
        /// </summary>
        public static string EditDeliveryBoy {
            get {
                return ResourceManager.GetString("EditDeliveryBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditDeliveryServiceVendor.
        /// </summary>
        public static string EditDeliveryServiceVendor {
            get {
                return ResourceManager.GetString("EditDeliveryServiceVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditDiningTable.
        /// </summary>
        public static string EditDiningTable {
            get {
                return ResourceManager.GetString("EditDiningTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditGRN.
        /// </summary>
        public static string EditGRN {
            get {
                return ResourceManager.GetString("EditGRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditGRRN.
        /// </summary>
        public static string EditGRRN {
            get {
                return ResourceManager.GetString("EditGRRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditItem.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditItemBarCode.
        /// </summary>
        public static string EditItemBarCode {
            get {
                return ResourceManager.GetString("EditItemBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditMainCategory.
        /// </summary>
        public static string EditMainCategory {
            get {
                return ResourceManager.GetString("EditMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditModifier.
        /// </summary>
        public static string EditModifier {
            get {
                return ResourceManager.GetString("EditModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditPO.
        /// </summary>
        public static string EditPO {
            get {
                return ResourceManager.GetString("EditPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditPurchase.
        /// </summary>
        public static string EditPurchase {
            get {
                return ResourceManager.GetString("EditPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditRestaurantFloor.
        /// </summary>
        public static string EditRestaurantFloor {
            get {
                return ResourceManager.GetString("EditRestaurantFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditRole.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSize.
        /// </summary>
        public static string EditSize {
            get {
                return ResourceManager.GetString("EditSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSubCategory.
        /// </summary>
        public static string EditSubCategory {
            get {
                return ResourceManager.GetString("EditSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditTax.
        /// </summary>
        public static string EditTax {
            get {
                return ResourceManager.GetString("EditTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditUnit.
        /// </summary>
        public static string EditUnit {
            get {
                return ResourceManager.GetString("EditUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditUser.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditVendor.
        /// </summary>
        public static string EditVendor {
            get {
                return ResourceManager.GetString("EditVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditWaiter.
        /// </summary>
        public static string EditWaiter {
            get {
                return ResourceManager.GetString("EditWaiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodsReceivedNotes.
        /// </summary>
        public static string GoodsReceivedNotes {
            get {
                return ResourceManager.GetString("GoodsReceivedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodsReturnNotes.
        /// </summary>
        public static string GoodsReturnNotes {
            get {
                return ResourceManager.GetString("GoodsReturnNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRNDetails.
        /// </summary>
        public static string GRNDetails {
            get {
                return ResourceManager.GetString("GRNDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRRNDetails.
        /// </summary>
        public static string GRRNDetails {
            get {
                return ResourceManager.GetString("GRRNDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncomeStatement.
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventorySetup.
        /// </summary>
        public static string InventorySetup {
            get {
                return ResourceManager.GetString("InventorySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemBarCodeDetails.
        /// </summary>
        public static string ItemBarCodeDetails {
            get {
                return ResourceManager.GetString("ItemBarCodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemBarCodes.
        /// </summary>
        public static string ItemBarCodes {
            get {
                return ResourceManager.GetString("ItemBarCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDetails.
        /// </summary>
        public static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemsBulkUpload.
        /// </summary>
        public static string ItemsBulkUpload {
            get {
                return ResourceManager.GetString("ItemsBulkUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        public static string Ledger {
            get {
                return ResourceManager.GetString("Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Categories.
        /// </summary>
        public static string Main_Categories {
            get {
                return ResourceManager.GetString("Main Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainCategoryDetails.
        /// </summary>
        public static string MainCategoryDetails {
            get {
                return ResourceManager.GetString("MainCategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifierDetails.
        /// </summary>
        public static string ModifierDetails {
            get {
                return ResourceManager.GetString("ModifierDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayBill.
        /// </summary>
        public static string PayBill {
            get {
                return ResourceManager.GetString("PayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhysicalStocks.
        /// </summary>
        public static string PhysicalStocks {
            get {
                return ResourceManager.GetString("PhysicalStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceOrder.
        /// </summary>
        public static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODetails.
        /// </summary>
        public static string PODetails {
            get {
                return ResourceManager.GetString("PODetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOrderReceipt.
        /// </summary>
        public static string PrintOrderReceipt {
            get {
                return ResourceManager.GetString("PrintOrderReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseDetails.
        /// </summary>
        public static string PurchaseDetails {
            get {
                return ResourceManager.GetString("PurchaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseOrders.
        /// </summary>
        public static string PurchaseOrders {
            get {
                return ResourceManager.GetString("PurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantFloorDetails.
        /// </summary>
        public static string RestaurantFloorDetails {
            get {
                return ResourceManager.GetString("RestaurantFloorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantFloors.
        /// </summary>
        public static string RestaurantFloors {
            get {
                return ResourceManager.GetString("RestaurantFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantManagement.
        /// </summary>
        public static string RestaurantManagement {
            get {
                return ResourceManager.GetString("RestaurantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantPosFront.
        /// </summary>
        public static string RestaurantPosFront {
            get {
                return ResourceManager.GetString("RestaurantPosFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleDetails.
        /// </summary>
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesByDeliveryServices.
        /// </summary>
        public static string SalesByDeliveryServices {
            get {
                return ResourceManager.GetString("SalesByDeliveryServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesReports.
        /// </summary>
        public static string SalesReports {
            get {
                return ResourceManager.GetString("SalesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesReturn.
        /// </summary>
        public static string SalesReturn {
            get {
                return ResourceManager.GetString("SalesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeDetails.
        /// </summary>
        public static string SizeDetails {
            get {
                return ResourceManager.GetString("SizeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockManagement.
        /// </summary>
        public static string StockManagement {
            get {
                return ResourceManager.GetString("StockManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories.
        /// </summary>
        public static string Sub_Categories {
            get {
                return ResourceManager.GetString("Sub Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubCategoryDetails.
        /// </summary>
        public static string SubCategoryDetails {
            get {
                return ResourceManager.GetString("SubCategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxCollectionReport.
        /// </summary>
        public static string TaxCollectionReport {
            get {
                return ResourceManager.GetString("TaxCollectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxDetails.
        /// </summary>
        public static string TaxDetails {
            get {
                return ResourceManager.GetString("TaxDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrialBalance.
        /// </summary>
        public static string TrialBalance {
            get {
                return ResourceManager.GetString("TrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitDetails.
        /// </summary>
        public static string UnitDetails {
            get {
                return ResourceManager.GetString("UnitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnverifiedEntries.
        /// </summary>
        public static string UnverifiedEntries {
            get {
                return ResourceManager.GetString("UnverifiedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDetails.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VendorDetails.
        /// </summary>
        public static string VendorDetails {
            get {
                return ResourceManager.GetString("VendorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerifyJournalEntry.
        /// </summary>
        public static string VerifyJournalEntry {
            get {
                return ResourceManager.GetString("VerifyJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAccount.
        /// </summary>
        public static string ViewAccount {
            get {
                return ResourceManager.GetString("ViewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaiterDetails.
        /// </summary>
        public static string WaiterDetails {
            get {
                return ResourceManager.GetString("WaiterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiters.
        /// </summary>
        public static string Waiters {
            get {
                return ResourceManager.GetString("Waiters", resourceCulture);
            }
        }
    }
}
